package Bus;

public  class buses {
   public static   String []NineFourThree={ //994
        "Anand Vihar ISBT (Viveka Nand ISBT)",
        "Hasan Pur Depot (Patparganj Depot)",
        "Shakar Pur",
        "Rainy Well",
        "I.T.O. (Ring Road)",
        "Government Press Kali Mandir",
        "Shivaji Stadium / Sucheta Kriplani Hospital",
        "Panchkuian Road",
        "Sadhu Vaswani Marg Petrol Pump",
        "Pusa Road Telephone Exchange",
        "West Patel Nagar",
        "Karampura Terminal",
        "Punjabi Bagh Terminal",
        "Madi Pur JJ Colony",
        "Peera Garhi",
        "Mangol Puri B-Block",
        "Mangol Puri S-Block",
        "Sultan Puri Terminal"};
       public static String []sevenThree={ //73
            "Anand Vihar ISBT (Viveka Nand ISBT)",
            "Hasan Pur Depot (Patparganj Depot)",
            "Shakar Pur",
            "Rainy Well",
            "I.T.O. (AGCR)",
            "Mandi House",
            "Jantar Mantar",
            "Kendriya Terminal",
            "Upper Ridge Road",
            "Shankar Road",
            "West Patel Nagar",
            "Loha Mandi",
            "Naraina Vihar",
            "Maya Puri Depot",
            "Beri Wala Bagh",
            "Hari Nagar Clock Tower"};
            public  static    String []oneOneFourPlusNineNineZero={ //114+990E
                "Regal / Shivaji Stadium",
                "Shaheed Bhagat Singh Marg",
                "Shaheed Bhagat Singh Marg",
                "Gole Market",
                "PS Mandir Marg",
                "Balmiki Mandir",
                "Panchkuian Road Banwai Lal Hospital",
                "Meghdoot Bhawan",
                "Arya Samaj Road / Pusa Road Petrol Pump",
                "Karol Bagh Metro Station",
                "Rajendra Place / Karol Bagh Telephone Exchange",
                "East Patel Nagar",
                "South Patel Nagar (Metro Station)",
                "West Patel Nagar",
                "Shadipur DTC Colony Metro Station",
                "Shadi Pur Depot",
                "Moti Nagar Industrial Area",
                "Karampura Terminal",
                "B Block New Moti Nagar",
                "Punjabi Bagh Terminal",
                "Britannia (Shakurpur)",
                "Telephone Exchange",
                "Wazirpur Depot",
                "WazirpurDepotRoadNo41(SubhashPalaceMarket)",
                "Guru Govind Singh College",
                "TV Tower (Power House)",
                "DAV School",
                "Pitam Pura K.D. Block",
                "Pittampura AP-Block",
                "Pitampura CD-Block",
                "Pitam Pura Power House",
                "Madhuban Chowk (Outer Ring Road)",
                "Madhuban Chowk",
                "Rohini Sector 7/8 X-ing",
                "Sai Baba Chowk",
                "Rohini Sec 7/9",
                "Rohini West Metro Station",
                "Rohini Depot I",
                "Chhoturam Park Rohini Sec 5",
                "Rithala Crossing (Rohini Sec 6 Crossing)",
                "B-5 Rohini Som Bazar",
                "Rithala School",
                "Rithala Village",
                "Rithala School",
                "B-5 Rohini Som Bazar",
                "Rithala Crossing",
                "Visram Chowk",
                "Rohini Sec-3/4 Xing",
                "Avantika",
                "Avantika Crossing",
                "Mangol Pur Khurd",
                "Mangol Puri Y-Block",
                "Budh Vihar",
                "Krishna Vihar",
                "Brahm Shakti Hospital",
                "Pooth Kalan",
                "Rohini Sec-21",
                "Begumpur (Rohini)",
                "Rajeev Nagar",
                "Karala Pathsala Jain Mandir",
                "Sukhbir Nagar",
                "Rama Vihar",
                "Karala School",
                "Karala Village",
                "Karala Crossing",
                "DesuOffice(NDPL)",
                "Shiv Vihar Bheem Chowk",
                "RadhaSwamiSatsang/RupaliEnclave",
                "Shivam Plywood",
                "Kanjhawla",
                "Kanjhawla Village",
                "Kanjhawla Depot"};
                public  static   String []threeFiveOne={//351
                    "Anand Parbat",
                    "D.B. Gupta Market",
                    "Police Station Paharganj",
                    "New Delhi Railway Station",
                    "Mandi House",
                    "I.T.O. (AGCR)",
                    "Rainy Well",
                    "Mother Dairy",
                    "Trilok Puri 13-Block",
                    "Kalyan Puri",
                    "N.H. 8 X-ing",
                    "Gazi Pur Dairy Farm"
                };
                
            
                     
}
